import active1 from "../images/active1.png";
import tshirt1 from "../images/tshirt1.png";
import tshirt2 from "../images/tshirt1-1.png";
import tshirt3 from "../images/tshirt1-2.png";
import tshirt4 from "../images/tshirt1-3.png";
import color1 from "../images/color-1.png";
import color2 from "../images/color-2.png";
import p1 from "../images/p1.png";
import p2 from "../images/p2.png";
import p3 from "../images/p3.png";
import p4 from "../images/p4.png";

export const Data = [
  {
    id: 1,
    gender: "Men",
    category: "Clothing",
    type: "Tops",
    brand: "Adidas",
    product: "Adidas Black Tshirt",
    title:
      "Adidas black t-shirt lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    rating: 22,
    stars: 5,
    price: 9999,
    currentPrice: "9,999",
    currency: "LE",
    discount: "100%",
    size: "Large",
    images: { active1, tshirt1, tshirt2, tshirt3, tshirt4 },
    colors: { color1, color2 },
  },
  {
    id: 2,
    gender: "Women",
    category: "Clothing",
    type: "Tops",
    brand: "Adidas",
    product: "Adidas Black Tshirt",
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    rating: 22,
    stars: 4.2,
    price: 9999,
    currentPrice: "9,999",
    oldPrice: "9,999",
    currency: "LE",
    discount: "30%",
    size: "Large",
    images: { p1 },
    colors: { color1, color2 },
  },
  {
    id: 3,
    gender: "Women",
    category: "Clothing",
    type: "Tops",
    brand: "Adidas",
    product: "Adidas Black Tshirt",
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    rating: 22,
    stars: 4.2,
    price: 9999,
    currentPrice: "9,999",
    oldPrice: "9,999",
    currency: "LE",
    discount: "30%",
    size: "Large",
    images: { p2 },
    colors: { color1, color2 },
  },
  {
    id: 4,
    gender: "Men",
    category: "Clothing",
    type: "Tops",
    brand: "Adidas",
    product: "Adidas Black Tshirt",
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    rating: 22,
    stars: 4.2,
    price: 9999,
    currentPrice: "9,999",
    oldPrice: "9,999",
    currency: "LE",
    discount: "30%",
    size: "Large",
    images: { p3 },
    colors: { color1, color2 },
  },
  {
    id: 4,
    gender: "Men",
    category: "Clothing",
    type: "Tops",
    brand: "Adidas",
    product: "Adidas Black Tshirt",
    title: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
    rating: 22,
    stars: 4.2,
    price: 9999,
    currentPrice: "9,999",
    oldPrice: "9,999",
    currency: "LE",
    discount: "30%",
    size: "Large",
    images: { p4 },
    colors: { color1, color2 },
  },
];
